Metal: finalise implementation; register shader container types
These were getting registered in background threads and causing races:

```
ERROR: Class 'RenderingShaderContainer' already exists.
   at: _add_class (/Volumes/Data/projects/games/godot-shader-baker/core/object/class_db.cpp:848)
ERROR: Class 'RenderingShaderContainerMetal' already exists.
   at: _add_class (/Volumes/Data/projects/games/godot-shader-baker/core/object/class_db.cpp:848)
ERROR: Class 'RenderingShaderContainer' already exists.
   at: _add_class (/Volumes/Data/projects/games/godot-shader-baker/core/object/class_db.cpp:848)
ERROR: Class 'RenderingShaderContainerMetal' already exists.
   at: _add_class (/Volumes/Data/projects/games/godot-shader-baker/core/object/class_db.cpp:848)
```